/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChairmanRouteImport } from './routes/chairman'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ElderlyRouteImport } from './routes/elderly'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as InterwovenRouteImport } from './routes/interwoven'
import { Route as InvolvedRouteImport } from './routes/involved'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanRoute = ChairmanRouteImport.update({
  id: '/chairman',
  path: '/chairman',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderlyRoute = ElderlyRouteImport.update({
  id: '/elderly',
  path: '/elderly',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InterwovenRoute = InterwovenRouteImport.update({
  id: '/interwoven',
  path: '/interwoven',
  getParentRoute: () => rootRouteImport,
} as any)
const InvolvedRoute = InvolvedRouteImport.update({
  id: '/involved',
  path: '/involved',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chairman': typeof ChairmanRoute
  '/donate': typeof DonateRoute
  '/elderly': typeof ElderlyRoute
  '/impact': typeof ImpactRoute
  '/interwoven': typeof InterwovenRoute
  '/involved': typeof InvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/strategy': typeof StrategyRoute
  '/volunteer': typeof VolunteerRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chairman': typeof ChairmanRoute
  '/donate': typeof DonateRoute
  '/elderly': typeof ElderlyRoute
  '/impact': typeof ImpactRoute
  '/interwoven': typeof InterwovenRoute
  '/involved': typeof InvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/strategy': typeof StrategyRoute
  '/volunteer': typeof VolunteerRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chairman': typeof ChairmanRoute
  '/donate': typeof DonateRoute
  '/elderly': typeof ElderlyRoute
  '/impact': typeof ImpactRoute
  '/interwoven': typeof InterwovenRoute
  '/involved': typeof InvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/strategy': typeof StrategyRoute
  '/volunteer': typeof VolunteerRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chairman'
    | '/donate'
    | '/elderly'
    | '/impact'
    | '/interwoven'
    | '/involved'
    | '/leadership'
    | '/strategy'
    | '/volunteer'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chairman'
    | '/donate'
    | '/elderly'
    | '/impact'
    | '/interwoven'
    | '/involved'
    | '/leadership'
    | '/strategy'
    | '/volunteer'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chairman'
    | '/donate'
    | '/elderly'
    | '/impact'
    | '/interwoven'
    | '/involved'
    | '/leadership'
    | '/strategy'
    | '/volunteer'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChairmanRoute: typeof ChairmanRoute
  DonateRoute: typeof DonateRoute
  ElderlyRoute: typeof ElderlyRoute
  ImpactRoute: typeof ImpactRoute
  InterwovenRoute: typeof InterwovenRoute
  InvolvedRoute: typeof InvolvedRoute
  LeadershipRoute: typeof LeadershipRoute
  StrategyRoute: typeof StrategyRoute
  VolunteerRoute: typeof VolunteerRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman': {
      id: '/chairman'
      path: '/chairman'
      fullPath: '/chairman'
      preLoaderRoute: typeof ChairmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elderly': {
      id: '/elderly'
      path: '/elderly'
      fullPath: '/elderly'
      preLoaderRoute: typeof ElderlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interwoven': {
      id: '/interwoven'
      path: '/interwoven'
      fullPath: '/interwoven'
      preLoaderRoute: typeof InterwovenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/involved': {
      id: '/involved'
      path: '/involved'
      fullPath: '/involved'
      preLoaderRoute: typeof InvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChairmanRoute: ChairmanRoute,
  DonateRoute: DonateRoute,
  ElderlyRoute: ElderlyRoute,
  ImpactRoute: ImpactRoute,
  InterwovenRoute: InterwovenRoute,
  InvolvedRoute: InvolvedRoute,
  LeadershipRoute: LeadershipRoute,
  StrategyRoute: StrategyRoute,
  VolunteerRoute: VolunteerRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
